version: "3.9"
services:
  node:
    build: .
    ports:
      - 3000:3000
    environment: 
      - MONGO_PATH=mongodb://mongo:27017/vuttr
      - HOST=0.0.0.0
    links:
      - mongo
    networks:
      - net
  mongo:
    image: mongo:latest
    ports: 
      - 27017:27017
    networks:
      - net
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
networks: 
  net:
    driver: bridge   